services:
  knowledge-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal
    ports:
      - "127.0.0.1:3000:$PORT"
    env_file:
      - .env
    environment:
      SERVICE: knowledge
      SERVER_TO_RUN: http
      GOCACHE: /go-cachee
      KNOWLEDGE_WORKER_COUNT: 1
    depends_on:
      - memgraph

  memgraph:
    image: "memgraph/memgraph-mage"
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    ports:
      - "${MEMGRAPH_PORT}:7687"
      - "127.0.0.1:7444:7444"
    command: ["--log-level=TRACE"]
    environment:
      - MEMGRAPH_USER=${MEMGRAPH_USER}
      - MEMGRAPH_PASSWORD=${MEMGRAPH_PASSWORD}
  
  memgraph-lab:
    image: memgraph/lab:latest
    container_name: memgraph-lab
    ports:
      - "127.0.0.1:8000:3000"
    depends_on:
      - memgraph
    environment:
      - QUICK_CONNECT_MG_HOST=memgraph
      - QUICK_CONNECT_MG_PORT=7687

volumes:
  mg_lib:
  mg_log:
  mg_etc: