// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ports

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Messages  []Message          `json:"messages"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// ConversationList defines model for ConversationList.
type ConversationList struct {
	Items []ConversationSummary `json:"items"`
	Total int                   `json:"total"`
}

// ConversationSummary defines model for ConversationSummary.
type ConversationSummary struct {
	CreatedAt    time.Time          `json:"createdAt"`
	Id           openapi_types.UUID `json:"id"`
	MessageCount int                `json:"messageCount"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updatedAt"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	// Title Optional title; auto-generated from the first message if omitted when a message is sent
	Title *string `json:"title,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Message defines model for Message.
type Message struct {
	Content        string             `json:"content"`
	ConversationId openapi_types.UUID `json:"conversationId"`
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	Role           MessageRole        `json:"role"`

	// Sources Present on assistant messages when retrieval was used
	Sources *[]Source `json:"sources,omitempty"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageList defines model for MessageList.
type MessageList struct {
	Items []Message `json:"items"`
	Total int       `json:"total"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Content string `json:"content"`

	// HistoryCapacity Number of most recent messages in the conversation to include as LLM context
	HistoryCapacity *int `json:"historyCapacity,omitempty"`

	// Tags Optional tag filter passed to Knowledge retrieval
	Tags *[]string `json:"tags,omitempty"`

	// TopK Number of knowledge chunks to retrieve
	TopK *int `json:"topK,omitempty"`
}

// SendMessageResult defines model for SendMessageResult.
type SendMessageResult struct {
	AssistantMessage Message `json:"assistantMessage"`
	UserMessage      Message `json:"userMessage"`
}

// Source defines model for Source.
type Source struct {
	ChunkId       *string            `json:"chunkId,omitempty"`
	DocumentId    openapi_types.UUID `json:"documentId"`
	DocumentTitle string             `json:"documentTitle"`
	Score         float32            `json:"score"`
	Text          string             `json:"text"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest
