/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IndexStatus from './IndexStatus';

/**
 * The DocumentSummary model module.
 * @module model/DocumentSummary
 * @version 1.0.0
 */
class DocumentSummary {
    /**
     * Constructs a new <code>DocumentSummary</code>.
     * @alias module:model/DocumentSummary
     * @param id {String} 
     * @param title {String} 
     * @param tags {Array.<String>} 
     * @param indexStatus {module:model/IndexStatus} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, title, tags, indexStatus, createdAt, updatedAt) { 
        
        DocumentSummary.initialize(this, id, title, tags, indexStatus, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, title, tags, indexStatus, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['title'] = title;
        obj['tags'] = tags;
        obj['indexStatus'] = indexStatus;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>DocumentSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentSummary} obj Optional instance to populate.
     * @return {module:model/DocumentSummary} The populated <code>DocumentSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentSummary();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('indexStatus')) {
                obj['indexStatus'] = IndexStatus.constructFromObject(data['indexStatus']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DocumentSummary.prototype['id'] = undefined;

/**
 * @member {String} title
 */
DocumentSummary.prototype['title'] = undefined;

/**
 * @member {Array.<String>} tags
 */
DocumentSummary.prototype['tags'] = undefined;

/**
 * @member {module:model/IndexStatus} indexStatus
 */
DocumentSummary.prototype['indexStatus'] = undefined;

/**
 * @member {Date} createdAt
 */
DocumentSummary.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
DocumentSummary.prototype['updatedAt'] = undefined;






export default DocumentSummary;

