/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentSummary from './DocumentSummary';

/**
 * The DocumentList model module.
 * @module model/DocumentList
 * @version 1.0.0
 */
class DocumentList {
    /**
     * Constructs a new <code>DocumentList</code>.
     * @alias module:model/DocumentList
     * @param items {Array.<module:model/DocumentSummary>} 
     * @param total {Number} 
     */
    constructor(items, total) { 
        
        DocumentList.initialize(this, items, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items, total) { 
        obj['items'] = items;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>DocumentList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DocumentList} obj Optional instance to populate.
     * @return {module:model/DocumentList} The populated <code>DocumentList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocumentList();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [DocumentSummary]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/DocumentSummary>} items
 */
DocumentList.prototype['items'] = undefined;

/**
 * @member {Number} total
 */
DocumentList.prototype['total'] = undefined;






export default DocumentList;

