/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class IndexStatus.
* @enum {}
* @readonly
*/
export default class IndexStatus {
    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "processing"
         * @const
         */
        "processing" = "processing";

    
        /**
         * value: "ready"
         * @const
         */
        "ready" = "ready";

    
        /**
         * value: "failed"
         * @const
         */
        "failed" = "failed";

    

    /**
    * Returns a <code>IndexStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/IndexStatus} The enum <code>IndexStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

