/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IndexStatus from './IndexStatus';

/**
 * The IndexJob model module.
 * @module model/IndexJob
 * @version 1.0.0
 */
class IndexJob {
    /**
     * Constructs a new <code>IndexJob</code>.
     * @alias module:model/IndexJob
     * @param documentId {String} 
     * @param status {module:model/IndexStatus} 
     */
    constructor(documentId, status) { 
        
        IndexJob.initialize(this, documentId, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentId, status) { 
        obj['documentId'] = documentId;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>IndexJob</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexJob} obj Optional instance to populate.
     * @return {module:model/IndexJob} The populated <code>IndexJob</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IndexJob();

            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = IndexStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
            }
            if (data.hasOwnProperty('finishedAt')) {
                obj['finishedAt'] = ApiClient.convertToType(data['finishedAt'], 'Date');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} documentId
 */
IndexJob.prototype['documentId'] = undefined;

/**
 * @member {module:model/IndexStatus} status
 */
IndexJob.prototype['status'] = undefined;

/**
 * @member {Date} startedAt
 */
IndexJob.prototype['startedAt'] = undefined;

/**
 * @member {Date} finishedAt
 */
IndexJob.prototype['finishedAt'] = undefined;

/**
 * @member {String} errorMessage
 */
IndexJob.prototype['errorMessage'] = undefined;






export default IndexJob;

