/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RetrievedChunk model module.
 * @module model/RetrievedChunk
 * @version 1.0.0
 */
class RetrievedChunk {
    /**
     * Constructs a new <code>RetrievedChunk</code>.
     * @alias module:model/RetrievedChunk
     * @param documentId {String} 
     * @param documentTitle {String} 
     * @param text {String} 
     * @param score {Number} 
     */
    constructor(documentId, documentTitle, text, score) { 
        
        RetrievedChunk.initialize(this, documentId, documentTitle, text, score);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, documentId, documentTitle, text, score) { 
        obj['documentId'] = documentId;
        obj['documentTitle'] = documentTitle;
        obj['text'] = text;
        obj['score'] = score;
    }

    /**
     * Constructs a <code>RetrievedChunk</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RetrievedChunk} obj Optional instance to populate.
     * @return {module:model/RetrievedChunk} The populated <code>RetrievedChunk</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RetrievedChunk();

            if (data.hasOwnProperty('documentId')) {
                obj['documentId'] = ApiClient.convertToType(data['documentId'], 'String');
            }
            if (data.hasOwnProperty('documentTitle')) {
                obj['documentTitle'] = ApiClient.convertToType(data['documentTitle'], 'String');
            }
            if (data.hasOwnProperty('chunkId')) {
                obj['chunkId'] = ApiClient.convertToType(data['chunkId'], 'String');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('graphPath')) {
                obj['graphPath'] = ApiClient.convertToType(data['graphPath'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} documentId
 */
RetrievedChunk.prototype['documentId'] = undefined;

/**
 * @member {String} documentTitle
 */
RetrievedChunk.prototype['documentTitle'] = undefined;

/**
 * @member {String} chunkId
 */
RetrievedChunk.prototype['chunkId'] = undefined;

/**
 * @member {String} text
 */
RetrievedChunk.prototype['text'] = undefined;

/**
 * @member {Number} score
 */
RetrievedChunk.prototype['score'] = undefined;

/**
 * Optional graph traversal path for explainability
 * @member {Array.<String>} graphPath
 */
RetrievedChunk.prototype['graphPath'] = undefined;






export default RetrievedChunk;

