/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RetrieveRequest model module.
 * @module model/RetrieveRequest
 * @version 1.0.0
 */
class RetrieveRequest {
    /**
     * Constructs a new <code>RetrieveRequest</code>.
     * @alias module:model/RetrieveRequest
     * @param query {String} 
     */
    constructor(query) { 
        
        RetrieveRequest.initialize(this, query);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, query) { 
        obj['query'] = query;
    }

    /**
     * Constructs a <code>RetrieveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RetrieveRequest} obj Optional instance to populate.
     * @return {module:model/RetrieveRequest} The populated <code>RetrieveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RetrieveRequest();

            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('topK')) {
                obj['topK'] = ApiClient.convertToType(data['topK'], 'Number');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} query
 */
RetrieveRequest.prototype['query'] = undefined;

/**
 * @member {Number} topK
 * @default 5
 */
RetrieveRequest.prototype['topK'] = 5;

/**
 * Optional tag filter
 * @member {Array.<String>} tags
 */
RetrieveRequest.prototype['tags'] = undefined;






export default RetrieveRequest;

