/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RetrievedChunk from './RetrievedChunk';

/**
 * The RetrieveResponse model module.
 * @module model/RetrieveResponse
 * @version 1.0.0
 */
class RetrieveResponse {
    /**
     * Constructs a new <code>RetrieveResponse</code>.
     * @alias module:model/RetrieveResponse
     * @param query {String} 
     * @param chunks {Array.<module:model/RetrievedChunk>} 
     */
    constructor(query, chunks) { 
        
        RetrieveResponse.initialize(this, query, chunks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, query, chunks) { 
        obj['query'] = query;
        obj['chunks'] = chunks;
    }

    /**
     * Constructs a <code>RetrieveResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RetrieveResponse} obj Optional instance to populate.
     * @return {module:model/RetrieveResponse} The populated <code>RetrieveResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RetrieveResponse();

            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('chunks')) {
                obj['chunks'] = ApiClient.convertToType(data['chunks'], [RetrievedChunk]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} query
 */
RetrieveResponse.prototype['query'] = undefined;

/**
 * @member {Array.<module:model/RetrievedChunk>} chunks
 */
RetrieveResponse.prototype['chunks'] = undefined;






export default RetrieveResponse;

