/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateDocumentRequest model module.
 * @module model/UpdateDocumentRequest
 * @version 1.0.0
 */
class UpdateDocumentRequest {
    /**
     * Constructs a new <code>UpdateDocumentRequest</code>.
     * @alias module:model/UpdateDocumentRequest
     */
    constructor() { 
        
        UpdateDocumentRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDocumentRequest} obj Optional instance to populate.
     * @return {module:model/UpdateDocumentRequest} The populated <code>UpdateDocumentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDocumentRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} title
 */
UpdateDocumentRequest.prototype['title'] = undefined;

/**
 * Markdown content
 * @member {String} content
 */
UpdateDocumentRequest.prototype['content'] = undefined;

/**
 * @member {Array.<String>} tags
 */
UpdateDocumentRequest.prototype['tags'] = undefined;






export default UpdateDocumentRequest;

