// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: knowledge.proto

package knowledge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexStatus int32

const (
	IndexStatus_INDEX_STATUS_UNSPECIFIED IndexStatus = 0
	IndexStatus_INDEX_STATUS_PENDING     IndexStatus = 1
	IndexStatus_INDEX_STATUS_PROCESSING  IndexStatus = 2
	IndexStatus_INDEX_STATUS_READY       IndexStatus = 3
	IndexStatus_INDEX_STATUS_FAILED      IndexStatus = 4
)

// Enum value maps for IndexStatus.
var (
	IndexStatus_name = map[int32]string{
		0: "INDEX_STATUS_UNSPECIFIED",
		1: "INDEX_STATUS_PENDING",
		2: "INDEX_STATUS_PROCESSING",
		3: "INDEX_STATUS_READY",
		4: "INDEX_STATUS_FAILED",
	}
	IndexStatus_value = map[string]int32{
		"INDEX_STATUS_UNSPECIFIED": 0,
		"INDEX_STATUS_PENDING":     1,
		"INDEX_STATUS_PROCESSING":  2,
		"INDEX_STATUS_READY":       3,
		"INDEX_STATUS_FAILED":      4,
	}
)

func (x IndexStatus) Enum() *IndexStatus {
	p := new(IndexStatus)
	*p = x
	return p
}

func (x IndexStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledge_proto_enumTypes[0].Descriptor()
}

func (IndexStatus) Type() protoreflect.EnumType {
	return &file_knowledge_proto_enumTypes[0]
}

func (x IndexStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexStatus.Descriptor instead.
func (IndexStatus) EnumDescriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{0}
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	IndexStatus   IndexStatus            `protobuf:"varint,4,opt,name=index_status,json=indexStatus,proto3,enum=knowledge.IndexStatus" json:"index_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *ListDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDocumentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDocumentsRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ListDocumentsRequest) GetIndexStatus() IndexStatus {
	if x != nil {
		return x.IndexStatus
	}
	return IndexStatus_INDEX_STATUS_UNSPECIFIED
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentSummary     `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *ListDocumentsResponse) GetDocuments() []*DocumentSummary {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDocumentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateDocumentRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ReindexDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexDocumentRequest) Reset() {
	*x = ReindexDocumentRequest{}
	mi := &file_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexDocumentRequest) ProtoMessage() {}

func (x *ReindexDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexDocumentRequest.ProtoReflect.Descriptor instead.
func (*ReindexDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *ReindexDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ReindexDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *IndexJob              `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexDocumentResponse) Reset() {
	*x = ReindexDocumentResponse{}
	mi := &file_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexDocumentResponse) ProtoMessage() {}

func (x *ReindexDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexDocumentResponse.ProtoReflect.Descriptor instead.
func (*ReindexDocumentResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *ReindexDocumentResponse) GetJob() *IndexJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetDocumentIndexStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentIndexStatusRequest) Reset() {
	*x = GetDocumentIndexStatusRequest{}
	mi := &file_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentIndexStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentIndexStatusRequest) ProtoMessage() {}

func (x *GetDocumentIndexStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentIndexStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentIndexStatusRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *GetDocumentIndexStatusRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetDocumentIndexStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *IndexJob              `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentIndexStatusResponse) Reset() {
	*x = GetDocumentIndexStatusResponse{}
	mi := &file_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentIndexStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentIndexStatusResponse) ProtoMessage() {}

func (x *GetDocumentIndexStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentIndexStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentIndexStatusResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocumentIndexStatusResponse) GetJob() *IndexJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type RetrieveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveRequest) Reset() {
	*x = RetrieveRequest{}
	mi := &file_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveRequest) ProtoMessage() {}

func (x *RetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveRequest.ProtoReflect.Descriptor instead.
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *RetrieveRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RetrieveRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RetrieveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Chunks        []*RetrievedChunk      `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveResponse) Reset() {
	*x = RetrieveResponse{}
	mi := &file_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveResponse) ProtoMessage() {}

func (x *RetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveResponse.ProtoReflect.Descriptor instead.
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *RetrieveResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveResponse) GetChunks() []*RetrievedChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	IndexStatus   IndexStatus            `protobuf:"varint,5,opt,name=index_status,json=indexStatus,proto3,enum=knowledge.IndexStatus" json:"index_status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Document) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Document) GetIndexStatus() IndexStatus {
	if x != nil {
		return x.IndexStatus
	}
	return IndexStatus_INDEX_STATUS_UNSPECIFIED
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DocumentSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	IndexStatus   IndexStatus            `protobuf:"varint,4,opt,name=index_status,json=indexStatus,proto3,enum=knowledge.IndexStatus" json:"index_status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentSummary) Reset() {
	*x = DocumentSummary{}
	mi := &file_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentSummary) ProtoMessage() {}

func (x *DocumentSummary) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentSummary.ProtoReflect.Descriptor instead.
func (*DocumentSummary) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *DocumentSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentSummary) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DocumentSummary) GetIndexStatus() IndexStatus {
	if x != nil {
		return x.IndexStatus
	}
	return IndexStatus_INDEX_STATUS_UNSPECIFIED
}

func (x *DocumentSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DocumentSummary) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type IndexJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        IndexStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=knowledge.IndexStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexJob) Reset() {
	*x = IndexJob{}
	mi := &file_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexJob) ProtoMessage() {}

func (x *IndexJob) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexJob.ProtoReflect.Descriptor instead.
func (*IndexJob) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *IndexJob) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IndexJob) GetStatus() IndexStatus {
	if x != nil {
		return x.Status
	}
	return IndexStatus_INDEX_STATUS_UNSPECIFIED
}

func (x *IndexJob) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *IndexJob) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *IndexJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RetrievedChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentTitle string                 `protobuf:"bytes,2,opt,name=document_title,json=documentTitle,proto3" json:"document_title,omitempty"`
	ChunkId       string                 `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	GraphPath     []string               `protobuf:"bytes,6,rep,name=graph_path,json=graphPath,proto3" json:"graph_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedChunk) Reset() {
	*x = RetrievedChunk{}
	mi := &file_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedChunk) ProtoMessage() {}

func (x *RetrievedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedChunk.ProtoReflect.Descriptor instead.
func (*RetrievedChunk) Descriptor() ([]byte, []int) {
	return file_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *RetrievedChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetrievedChunk) GetDocumentTitle() string {
	if x != nil {
		return x.DocumentTitle
	}
	return ""
}

func (x *RetrievedChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *RetrievedChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RetrievedChunk) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievedChunk) GetGraphPath() []string {
	if x != nil {
		return x.GraphPath
	}
	return nil
}

var File_knowledge_proto protoreflect.FileDescriptor

const file_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x0fknowledge.proto\x12\tknowledge\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\x14ListDocumentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x129\n" +
	"\findex_status\x18\x04 \x01(\x0e2\x16.knowledge.IndexStatusR\vindexStatus\"g\n" +
	"\x15ListDocumentsResponse\x128\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1a.knowledge.DocumentSummaryR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"[\n" +
	"\x15CreateDocumentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"|\n" +
	"\x15UpdateDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"8\n" +
	"\x15DeleteDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"9\n" +
	"\x16ReindexDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"@\n" +
	"\x17ReindexDocumentResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.knowledge.IndexJobR\x03job\"@\n" +
	"\x1dGetDocumentIndexStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"G\n" +
	"\x1eGetDocumentIndexStatusResponse\x12%\n" +
	"\x03job\x18\x01 \x01(\v2\x13.knowledge.IndexJobR\x03job\"P\n" +
	"\x0fRetrieveRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"[\n" +
	"\x10RetrieveResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x121\n" +
	"\x06chunks\x18\x02 \x03(\v2\x19.knowledge.RetrievedChunkR\x06chunks\"\x8f\x02\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x129\n" +
	"\findex_status\x18\x05 \x01(\x0e2\x16.knowledge.IndexStatusR\vindexStatus\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfc\x01\n" +
	"\x0fDocumentSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x129\n" +
	"\findex_status\x18\x04 \x01(\x0e2\x16.knowledge.IndexStatusR\vindexStatus\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf8\x01\n" +
	"\bIndexJob\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.knowledge.IndexStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xbc\x01\n" +
	"\x0eRetrievedChunk\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12%\n" +
	"\x0edocument_title\x18\x02 \x01(\tR\rdocumentTitle\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\tR\achunkId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\x12\x1d\n" +
	"\n" +
	"graph_path\x18\x06 \x03(\tR\tgraphPath*\x93\x01\n" +
	"\vIndexStatus\x12\x1c\n" +
	"\x18INDEX_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INDEX_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17INDEX_STATUS_PROCESSING\x10\x02\x12\x16\n" +
	"\x12INDEX_STATUS_READY\x10\x03\x12\x17\n" +
	"\x13INDEX_STATUS_FAILED\x10\x042\xa5\x05\n" +
	"\x10KnowledgeService\x12T\n" +
	"\rListDocuments\x12\x1f.knowledge.ListDocumentsRequest\x1a .knowledge.ListDocumentsResponse\"\x00\x12I\n" +
	"\x0eCreateDocument\x12 .knowledge.CreateDocumentRequest\x1a\x13.knowledge.Document\"\x00\x12C\n" +
	"\vGetDocument\x12\x1d.knowledge.GetDocumentRequest\x1a\x13.knowledge.Document\"\x00\x12I\n" +
	"\x0eUpdateDocument\x12 .knowledge.UpdateDocumentRequest\x1a\x13.knowledge.Document\"\x00\x12L\n" +
	"\x0eDeleteDocument\x12 .knowledge.DeleteDocumentRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n" +
	"\x0fReindexDocument\x12!.knowledge.ReindexDocumentRequest\x1a\".knowledge.ReindexDocumentResponse\"\x00\x12o\n" +
	"\x16GetDocumentIndexStatus\x12(.knowledge.GetDocumentIndexStatusRequest\x1a).knowledge.GetDocumentIndexStatusResponse\"\x00\x12E\n" +
	"\bRetrieve\x12\x1a.knowledge.RetrieveRequest\x1a\x1b.knowledge.RetrieveResponse\"\x00B=Z;github.com/kimnattanan/graph-rag-service/internal/knowledgeb\x06proto3"

var (
	file_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_proto_rawDescData []byte
)

func file_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledge_proto_rawDesc), len(file_knowledge_proto_rawDesc)))
	})
	return file_knowledge_proto_rawDescData
}

var file_knowledge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_knowledge_proto_goTypes = []any{
	(IndexStatus)(0),                       // 0: knowledge.IndexStatus
	(*ListDocumentsRequest)(nil),           // 1: knowledge.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),          // 2: knowledge.ListDocumentsResponse
	(*CreateDocumentRequest)(nil),          // 3: knowledge.CreateDocumentRequest
	(*GetDocumentRequest)(nil),             // 4: knowledge.GetDocumentRequest
	(*UpdateDocumentRequest)(nil),          // 5: knowledge.UpdateDocumentRequest
	(*DeleteDocumentRequest)(nil),          // 6: knowledge.DeleteDocumentRequest
	(*ReindexDocumentRequest)(nil),         // 7: knowledge.ReindexDocumentRequest
	(*ReindexDocumentResponse)(nil),        // 8: knowledge.ReindexDocumentResponse
	(*GetDocumentIndexStatusRequest)(nil),  // 9: knowledge.GetDocumentIndexStatusRequest
	(*GetDocumentIndexStatusResponse)(nil), // 10: knowledge.GetDocumentIndexStatusResponse
	(*RetrieveRequest)(nil),                // 11: knowledge.RetrieveRequest
	(*RetrieveResponse)(nil),               // 12: knowledge.RetrieveResponse
	(*Document)(nil),                       // 13: knowledge.Document
	(*DocumentSummary)(nil),                // 14: knowledge.DocumentSummary
	(*IndexJob)(nil),                       // 15: knowledge.IndexJob
	(*RetrievedChunk)(nil),                 // 16: knowledge.RetrievedChunk
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 18: google.protobuf.Empty
}
var file_knowledge_proto_depIdxs = []int32{
	0,  // 0: knowledge.ListDocumentsRequest.index_status:type_name -> knowledge.IndexStatus
	14, // 1: knowledge.ListDocumentsResponse.documents:type_name -> knowledge.DocumentSummary
	15, // 2: knowledge.ReindexDocumentResponse.job:type_name -> knowledge.IndexJob
	15, // 3: knowledge.GetDocumentIndexStatusResponse.job:type_name -> knowledge.IndexJob
	16, // 4: knowledge.RetrieveResponse.chunks:type_name -> knowledge.RetrievedChunk
	0,  // 5: knowledge.Document.index_status:type_name -> knowledge.IndexStatus
	17, // 6: knowledge.Document.created_at:type_name -> google.protobuf.Timestamp
	17, // 7: knowledge.Document.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: knowledge.DocumentSummary.index_status:type_name -> knowledge.IndexStatus
	17, // 9: knowledge.DocumentSummary.created_at:type_name -> google.protobuf.Timestamp
	17, // 10: knowledge.DocumentSummary.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: knowledge.IndexJob.status:type_name -> knowledge.IndexStatus
	17, // 12: knowledge.IndexJob.started_at:type_name -> google.protobuf.Timestamp
	17, // 13: knowledge.IndexJob.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 14: knowledge.KnowledgeService.ListDocuments:input_type -> knowledge.ListDocumentsRequest
	3,  // 15: knowledge.KnowledgeService.CreateDocument:input_type -> knowledge.CreateDocumentRequest
	4,  // 16: knowledge.KnowledgeService.GetDocument:input_type -> knowledge.GetDocumentRequest
	5,  // 17: knowledge.KnowledgeService.UpdateDocument:input_type -> knowledge.UpdateDocumentRequest
	6,  // 18: knowledge.KnowledgeService.DeleteDocument:input_type -> knowledge.DeleteDocumentRequest
	7,  // 19: knowledge.KnowledgeService.ReindexDocument:input_type -> knowledge.ReindexDocumentRequest
	9,  // 20: knowledge.KnowledgeService.GetDocumentIndexStatus:input_type -> knowledge.GetDocumentIndexStatusRequest
	11, // 21: knowledge.KnowledgeService.Retrieve:input_type -> knowledge.RetrieveRequest
	2,  // 22: knowledge.KnowledgeService.ListDocuments:output_type -> knowledge.ListDocumentsResponse
	13, // 23: knowledge.KnowledgeService.CreateDocument:output_type -> knowledge.Document
	13, // 24: knowledge.KnowledgeService.GetDocument:output_type -> knowledge.Document
	13, // 25: knowledge.KnowledgeService.UpdateDocument:output_type -> knowledge.Document
	18, // 26: knowledge.KnowledgeService.DeleteDocument:output_type -> google.protobuf.Empty
	8,  // 27: knowledge.KnowledgeService.ReindexDocument:output_type -> knowledge.ReindexDocumentResponse
	10, // 28: knowledge.KnowledgeService.GetDocumentIndexStatus:output_type -> knowledge.GetDocumentIndexStatusResponse
	12, // 29: knowledge.KnowledgeService.Retrieve:output_type -> knowledge.RetrieveResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_knowledge_proto_init() }
func file_knowledge_proto_init() {
	if File_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledge_proto_rawDesc), len(file_knowledge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_proto_depIdxs,
		EnumInfos:         file_knowledge_proto_enumTypes,
		MessageInfos:      file_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_proto = out.File
	file_knowledge_proto_goTypes = nil
	file_knowledge_proto_depIdxs = nil
}
