/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraphRagServiceKnowledge);
  }
}(this, function(expect, GraphRagServiceKnowledge) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraphRagServiceKnowledge.UpdateDocumentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdateDocumentRequest', function() {
    it('should create an instance of UpdateDocumentRequest', function() {
      // uncomment below and update the code to test UpdateDocumentRequest
      //var instane = new GraphRagServiceKnowledge.UpdateDocumentRequest();
      //expect(instance).to.be.a(GraphRagServiceKnowledge.UpdateDocumentRequest);
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new GraphRagServiceKnowledge.UpdateDocumentRequest();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new GraphRagServiceKnowledge.UpdateDocumentRequest();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new GraphRagServiceKnowledge.UpdateDocumentRequest();
      //expect(instance).to.be();
    });

  });

}));
