/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Message from './Message';

/**
 * The ConversationDetailAllOf model module.
 * @module model/ConversationDetailAllOf
 * @version 1.0.0
 */
class ConversationDetailAllOf {
    /**
     * Constructs a new <code>ConversationDetailAllOf</code>.
     * @alias module:model/ConversationDetailAllOf
     * @param messages {Array.<module:model/Message>} 
     */
    constructor(messages) { 
        
        ConversationDetailAllOf.initialize(this, messages);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, messages) { 
        obj['messages'] = messages;
    }

    /**
     * Constructs a <code>ConversationDetailAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConversationDetailAllOf} obj Optional instance to populate.
     * @return {module:model/ConversationDetailAllOf} The populated <code>ConversationDetailAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationDetailAllOf();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], [Message]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Message>} messages
 */
ConversationDetailAllOf.prototype['messages'] = undefined;






export default ConversationDetailAllOf;

