/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConversationSummary from './ConversationSummary';

/**
 * The ConversationList model module.
 * @module model/ConversationList
 * @version 1.0.0
 */
class ConversationList {
    /**
     * Constructs a new <code>ConversationList</code>.
     * @alias module:model/ConversationList
     * @param items {Array.<module:model/ConversationSummary>} 
     * @param total {Number} 
     */
    constructor(items, total) { 
        
        ConversationList.initialize(this, items, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items, total) { 
        obj['items'] = items;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>ConversationList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConversationList} obj Optional instance to populate.
     * @return {module:model/ConversationList} The populated <code>ConversationList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConversationList();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [ConversationSummary]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ConversationSummary>} items
 */
ConversationList.prototype['items'] = undefined;

/**
 * @member {Number} total
 */
ConversationList.prototype['total'] = undefined;






export default ConversationList;

