/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateConversationRequest model module.
 * @module model/CreateConversationRequest
 * @version 1.0.0
 */
class CreateConversationRequest {
    /**
     * Constructs a new <code>CreateConversationRequest</code>.
     * @alias module:model/CreateConversationRequest
     */
    constructor() { 
        
        CreateConversationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateConversationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateConversationRequest} obj Optional instance to populate.
     * @return {module:model/CreateConversationRequest} The populated <code>CreateConversationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateConversationRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Optional title; auto-generated from the first message if omitted when a message is sent
 * @member {String} title
 */
CreateConversationRequest.prototype['title'] = undefined;






export default CreateConversationRequest;

