/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Message from './Message';

/**
 * The MessageList model module.
 * @module model/MessageList
 * @version 1.0.0
 */
class MessageList {
    /**
     * Constructs a new <code>MessageList</code>.
     * @alias module:model/MessageList
     * @param items {Array.<module:model/Message>} 
     * @param total {Number} 
     */
    constructor(items, total) { 
        
        MessageList.initialize(this, items, total);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, items, total) { 
        obj['items'] = items;
        obj['total'] = total;
    }

    /**
     * Constructs a <code>MessageList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageList} obj Optional instance to populate.
     * @return {module:model/MessageList} The populated <code>MessageList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageList();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Message]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Message>} items
 */
MessageList.prototype['items'] = undefined;

/**
 * @member {Number} total
 */
MessageList.prototype['total'] = undefined;






export default MessageList;

