/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Source from './Source';

/**
 * The Message model module.
 * @module model/Message
 * @version 1.0.0
 */
class Message {
    /**
     * Constructs a new <code>Message</code>.
     * @alias module:model/Message
     * @param id {String} 
     * @param conversationId {String} 
     * @param role {module:model/Message.RoleEnum} 
     * @param content {String} 
     * @param createdAt {Date} 
     */
    constructor(id, conversationId, role, content, createdAt) { 
        
        Message.initialize(this, id, conversationId, role, content, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, conversationId, role, content, createdAt) { 
        obj['id'] = id;
        obj['conversationId'] = conversationId;
        obj['role'] = role;
        obj['content'] = content;
        obj['createdAt'] = createdAt;
    }

    /**
     * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Message} obj Optional instance to populate.
     * @return {module:model/Message} The populated <code>Message</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Message();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('conversationId')) {
                obj['conversationId'] = ApiClient.convertToType(data['conversationId'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('sources')) {
                obj['sources'] = ApiClient.convertToType(data['sources'], [Source]);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Message.prototype['id'] = undefined;

/**
 * @member {String} conversationId
 */
Message.prototype['conversationId'] = undefined;

/**
 * @member {module:model/Message.RoleEnum} role
 */
Message.prototype['role'] = undefined;

/**
 * @member {String} content
 */
Message.prototype['content'] = undefined;

/**
 * Present on assistant messages when retrieval was used
 * @member {Array.<module:model/Source>} sources
 */
Message.prototype['sources'] = undefined;

/**
 * @member {Date} createdAt
 */
Message.prototype['createdAt'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
Message['RoleEnum'] = {

    /**
     * value: "user"
     * @const
     */
    "user": "user",

    /**
     * value: "assistant"
     * @const
     */
    "assistant": "assistant"
};



export default Message;

