/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Message from './Message';

/**
 * The SendMessageResult model module.
 * @module model/SendMessageResult
 * @version 1.0.0
 */
class SendMessageResult {
    /**
     * Constructs a new <code>SendMessageResult</code>.
     * @alias module:model/SendMessageResult
     * @param userMessage {module:model/Message} 
     * @param assistantMessage {module:model/Message} 
     */
    constructor(userMessage, assistantMessage) { 
        
        SendMessageResult.initialize(this, userMessage, assistantMessage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userMessage, assistantMessage) { 
        obj['userMessage'] = userMessage;
        obj['assistantMessage'] = assistantMessage;
    }

    /**
     * Constructs a <code>SendMessageResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendMessageResult} obj Optional instance to populate.
     * @return {module:model/SendMessageResult} The populated <code>SendMessageResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendMessageResult();

            if (data.hasOwnProperty('userMessage')) {
                obj['userMessage'] = Message.constructFromObject(data['userMessage']);
            }
            if (data.hasOwnProperty('assistantMessage')) {
                obj['assistantMessage'] = Message.constructFromObject(data['assistantMessage']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Message} userMessage
 */
SendMessageResult.prototype['userMessage'] = undefined;

/**
 * @member {module:model/Message} assistantMessage
 */
SendMessageResult.prototype['assistantMessage'] = undefined;






export default SendMessageResult;

