/**
 * Graph RAG Service - Knowledge
 * Document CRUD, indexing, and retrieval over the knowledge graph.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateDocumentRequest from './model/CreateDocumentRequest';
import Document from './model/Document';
import DocumentList from './model/DocumentList';
import DocumentSummary from './model/DocumentSummary';
import Error from './model/Error';
import IndexJob from './model/IndexJob';
import IndexStatus from './model/IndexStatus';
import RetrieveRequest from './model/RetrieveRequest';
import RetrieveResult from './model/RetrieveResult';
import RetrievedChunk from './model/RetrievedChunk';
import UpdateDocumentRequest from './model/UpdateDocumentRequest';
import DefaultApi from './api/DefaultApi';


/**
* Document_CRUD_indexing_and_retrieval_over_the_knowledge_graph_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GraphRagServiceKnowledge = require('index'); // See note below*.
* var xxxSvc = new GraphRagServiceKnowledge.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GraphRagServiceKnowledge.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GraphRagServiceKnowledge.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GraphRagServiceKnowledge.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateDocumentRequest model constructor.
     * @property {module:model/CreateDocumentRequest}
     */
    CreateDocumentRequest,

    /**
     * The Document model constructor.
     * @property {module:model/Document}
     */
    Document,

    /**
     * The DocumentList model constructor.
     * @property {module:model/DocumentList}
     */
    DocumentList,

    /**
     * The DocumentSummary model constructor.
     * @property {module:model/DocumentSummary}
     */
    DocumentSummary,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The IndexJob model constructor.
     * @property {module:model/IndexJob}
     */
    IndexJob,

    /**
     * The IndexStatus model constructor.
     * @property {module:model/IndexStatus}
     */
    IndexStatus,

    /**
     * The RetrieveRequest model constructor.
     * @property {module:model/RetrieveRequest}
     */
    RetrieveRequest,

    /**
     * The RetrieveResult model constructor.
     * @property {module:model/RetrieveResult}
     */
    RetrieveResult,

    /**
     * The RetrievedChunk model constructor.
     * @property {module:model/RetrievedChunk}
     */
    RetrievedChunk,

    /**
     * The UpdateDocumentRequest model constructor.
     * @property {module:model/UpdateDocumentRequest}
     */
    UpdateDocumentRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
