/**
 * Graph RAG Service - User
 * Authentication, authorization, and user management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthResult from './model/AuthResult';
import CreateUserRequest from './model/CreateUserRequest';
import Error from './model/Error';
import LoginRequest from './model/LoginRequest';
import Permissions from './model/Permissions';
import RefreshRequest from './model/RefreshRequest';
import RegisterRequest from './model/RegisterRequest';
import UpdateUserRequest from './model/UpdateUserRequest';
import User from './model/User';
import UserList from './model/UserList';
import DefaultApi from './api/DefaultApi';


/**
* Authentication_authorization_and_user_management_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GraphRagServiceUser = require('index'); // See note below*.
* var xxxSvc = new GraphRagServiceUser.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GraphRagServiceUser.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GraphRagServiceUser.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GraphRagServiceUser.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthResult model constructor.
     * @property {module:model/AuthResult}
     */
    AuthResult,

    /**
     * The CreateUserRequest model constructor.
     * @property {module:model/CreateUserRequest}
     */
    CreateUserRequest,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The LoginRequest model constructor.
     * @property {module:model/LoginRequest}
     */
    LoginRequest,

    /**
     * The Permissions model constructor.
     * @property {module:model/Permissions}
     */
    Permissions,

    /**
     * The RefreshRequest model constructor.
     * @property {module:model/RefreshRequest}
     */
    RefreshRequest,

    /**
     * The RegisterRequest model constructor.
     * @property {module:model/RegisterRequest}
     */
    RegisterRequest,

    /**
     * The UpdateUserRequest model constructor.
     * @property {module:model/UpdateUserRequest}
     */
    UpdateUserRequest,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserList model constructor.
     * @property {module:model/UserList}
     */
    UserList,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
