// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ports

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for IndexStatus.
const (
	Failed     IndexStatus = "failed"
	Pending    IndexStatus = "pending"
	Processing IndexStatus = "processing"
	Ready      IndexStatus = "ready"
)

// Valid indicates whether the value is a known member of the IndexStatus enum.
func (e IndexStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Processing:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// CreateDocumentRequest defines model for CreateDocumentRequest.
type CreateDocumentRequest struct {
	// Content Markdown content
	Content string    `json:"content"`
	Tags    *[]string `json:"tags,omitempty"`
	Title   string    `json:"title"`
}

// Document defines model for Document.
type Document struct {
	Content     string             `json:"content"`
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	IndexStatus IndexStatus        `json:"indexStatus"`
	Tags        []string           `json:"tags"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// DocumentList defines model for DocumentList.
type DocumentList struct {
	Items []DocumentSummary `json:"items"`
	Total int               `json:"total"`
}

// DocumentSummary defines model for DocumentSummary.
type DocumentSummary struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Id          openapi_types.UUID `json:"id"`
	IndexStatus IndexStatus        `json:"indexStatus"`
	Tags        []string           `json:"tags"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// IndexJob defines model for IndexJob.
type IndexJob struct {
	DocumentId   openapi_types.UUID `json:"documentId"`
	ErrorMessage *string            `json:"errorMessage,omitempty"`
	FinishedAt   *time.Time         `json:"finishedAt,omitempty"`
	StartedAt    *time.Time         `json:"startedAt,omitempty"`
	Status       IndexStatus        `json:"status"`
}

// IndexStatus defines model for IndexStatus.
type IndexStatus string

// RetrieveRequest defines model for RetrieveRequest.
type RetrieveRequest struct {
	Query string `json:"query"`

	// Tags Optional tag filter
	Tags *[]string `json:"tags,omitempty"`
	TopK *int      `json:"topK,omitempty"`
}

// RetrieveResult defines model for RetrieveResult.
type RetrieveResult struct {
	Chunks []RetrievedChunk `json:"chunks"`
	Query  string           `json:"query"`
}

// RetrievedChunk defines model for RetrievedChunk.
type RetrievedChunk struct {
	ChunkId       *string            `json:"chunkId,omitempty"`
	DocumentId    openapi_types.UUID `json:"documentId"`
	DocumentTitle string             `json:"documentTitle"`

	// GraphPath Optional graph traversal path for explainability
	GraphPath *[]string `json:"graphPath,omitempty"`
	Score     float32   `json:"score"`
	Text      string    `json:"text"`
}

// UpdateDocumentRequest defines model for UpdateDocumentRequest.
type UpdateDocumentRequest struct {
	// Content Markdown content
	Content *string   `json:"content,omitempty"`
	Tags    *[]string `json:"tags,omitempty"`
	Title   *string   `json:"title,omitempty"`
}

// ListDocumentsParams defines parameters for ListDocuments.
type ListDocumentsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Tag Filter by tag
	Tag         *string      `form:"tag,omitempty" json:"tag,omitempty"`
	IndexStatus *IndexStatus `form:"indexStatus,omitempty" json:"indexStatus,omitempty"`
}

// CreateDocumentJSONRequestBody defines body for CreateDocument for application/json ContentType.
type CreateDocumentJSONRequestBody = CreateDocumentRequest

// UpdateDocumentJSONRequestBody defines body for UpdateDocument for application/json ContentType.
type UpdateDocumentJSONRequestBody = UpdateDocumentRequest

// RetrieveJSONRequestBody defines body for Retrieve for application/json ContentType.
type RetrieveJSONRequestBody = RetrieveRequest
