/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Conversation from './model/Conversation';
import ConversationDetail from './model/ConversationDetail';
import ConversationDetailAllOf from './model/ConversationDetailAllOf';
import ConversationList from './model/ConversationList';
import ConversationSummary from './model/ConversationSummary';
import CreateConversationRequest from './model/CreateConversationRequest';
import Error from './model/Error';
import Message from './model/Message';
import MessageList from './model/MessageList';
import SendMessageRequest from './model/SendMessageRequest';
import SendMessageResult from './model/SendMessageResult';
import Source from './model/Source';
import DefaultApi from './api/DefaultApi';


/**
* Conversation_and_message_storage_with_retrieval_augmented_generation_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GraphRagServiceConversation = require('index'); // See note below*.
* var xxxSvc = new GraphRagServiceConversation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GraphRagServiceConversation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GraphRagServiceConversation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GraphRagServiceConversation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Conversation model constructor.
     * @property {module:model/Conversation}
     */
    Conversation,

    /**
     * The ConversationDetail model constructor.
     * @property {module:model/ConversationDetail}
     */
    ConversationDetail,

    /**
     * The ConversationDetailAllOf model constructor.
     * @property {module:model/ConversationDetailAllOf}
     */
    ConversationDetailAllOf,

    /**
     * The ConversationList model constructor.
     * @property {module:model/ConversationList}
     */
    ConversationList,

    /**
     * The ConversationSummary model constructor.
     * @property {module:model/ConversationSummary}
     */
    ConversationSummary,

    /**
     * The CreateConversationRequest model constructor.
     * @property {module:model/CreateConversationRequest}
     */
    CreateConversationRequest,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MessageList model constructor.
     * @property {module:model/MessageList}
     */
    MessageList,

    /**
     * The SendMessageRequest model constructor.
     * @property {module:model/SendMessageRequest}
     */
    SendMessageRequest,

    /**
     * The SendMessageResult model constructor.
     * @property {module:model/SendMessageResult}
     */
    SendMessageResult,

    /**
     * The Source model constructor.
     * @property {module:model/Source}
     */
    Source,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
