/**
 * Graph RAG Service - User
 * Authentication, authorization, and user management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The AuthResult model module.
 * @module model/AuthResult
 * @version 1.0.0
 */
class AuthResult {
    /**
     * Constructs a new <code>AuthResult</code>.
     * @alias module:model/AuthResult
     * @param accessToken {String} 
     * @param refreshToken {String} 
     * @param expiresIn {Number} Access token lifetime in seconds
     * @param tokenType {String} 
     * @param user {module:model/User} 
     */
    constructor(accessToken, refreshToken, expiresIn, tokenType, user) { 
        
        AuthResult.initialize(this, accessToken, refreshToken, expiresIn, tokenType, user);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accessToken, refreshToken, expiresIn, tokenType, user) { 
        obj['accessToken'] = accessToken;
        obj['refreshToken'] = refreshToken;
        obj['expiresIn'] = expiresIn;
        obj['tokenType'] = tokenType;
        obj['user'] = user;
    }

    /**
     * Constructs a <code>AuthResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthResult} obj Optional instance to populate.
     * @return {module:model/AuthResult} The populated <code>AuthResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthResult();

            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
            if (data.hasOwnProperty('refreshToken')) {
                obj['refreshToken'] = ApiClient.convertToType(data['refreshToken'], 'String');
            }
            if (data.hasOwnProperty('expiresIn')) {
                obj['expiresIn'] = ApiClient.convertToType(data['expiresIn'], 'Number');
            }
            if (data.hasOwnProperty('tokenType')) {
                obj['tokenType'] = ApiClient.convertToType(data['tokenType'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} accessToken
 */
AuthResult.prototype['accessToken'] = undefined;

/**
 * @member {String} refreshToken
 */
AuthResult.prototype['refreshToken'] = undefined;

/**
 * Access token lifetime in seconds
 * @member {Number} expiresIn
 */
AuthResult.prototype['expiresIn'] = undefined;

/**
 * @member {String} tokenType
 */
AuthResult.prototype['tokenType'] = undefined;

/**
 * @member {module:model/User} user
 */
AuthResult.prototype['user'] = undefined;






export default AuthResult;

