/**
 * Graph RAG Service - User
 * Authentication, authorization, and user management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Permissions model module.
 * @module model/Permissions
 * @version 1.0.0
 */
class Permissions {
    /**
     * Constructs a new <code>Permissions</code>.
     * @alias module:model/Permissions
     * @param permissions {Array.<module:model/Permissions.PermissionsEnum>} 
     */
    constructor(permissions) { 
        
        Permissions.initialize(this, permissions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, permissions) { 
        obj['permissions'] = permissions;
    }

    /**
     * Constructs a <code>Permissions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Permissions} obj Optional instance to populate.
     * @return {module:model/Permissions} The populated <code>Permissions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Permissions();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Permissions.PermissionsEnum>} permissions
 */
Permissions.prototype['permissions'] = undefined;





/**
 * Allowed values for the <code>permissions</code> property.
 * @enum {String}
 * @readonly
 */
Permissions['PermissionsEnum'] = {

    /**
     * value: "knowledge:write"
     * @const
     */
    "knowledge:write": "knowledge:write",

    /**
     * value: "conversation:ask"
     * @const
     */
    "conversation:ask": "conversation:ask"
};



export default Permissions;

