/**
 * Graph RAG Service - User
 * Authentication, authorization, and user management.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param id {String} 
     * @param email {String} 
     * @param displayName {String} 
     * @param role {module:model/User.RoleEnum} 
     * @param permissions {Array.<module:model/User.PermissionsEnum>} 
     * @param createdAt {Date} 
     */
    constructor(id, email, displayName, role, permissions, createdAt) { 
        
        User.initialize(this, id, email, displayName, role, permissions, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, email, displayName, role, permissions, createdAt) { 
        obj['id'] = id;
        obj['email'] = email;
        obj['displayName'] = displayName;
        obj['role'] = role;
        obj['permissions'] = permissions;
        obj['createdAt'] = createdAt;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], ['String']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} displayName
 */
User.prototype['displayName'] = undefined;

/**
 * @member {module:model/User.RoleEnum} role
 */
User.prototype['role'] = undefined;

/**
 * @member {Array.<module:model/User.PermissionsEnum>} permissions
 */
User.prototype['permissions'] = undefined;

/**
 * @member {Date} createdAt
 */
User.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
User.prototype['updatedAt'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
User['RoleEnum'] = {

    /**
     * value: "admin"
     * @const
     */
    "admin": "admin",

    /**
     * value: "user"
     * @const
     */
    "user": "user"
};


/**
 * Allowed values for the <code>permissions</code> property.
 * @enum {String}
 * @readonly
 */
User['PermissionsEnum'] = {

    /**
     * value: "knowledge:write"
     * @const
     */
    "knowledge:write": "knowledge:write",

    /**
     * value: "conversation:ask"
     * @const
     */
    "conversation:ask": "conversation:ask"
};



export default User;

