/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraphRagServiceConversation);
  }
}(this, function(expect, GraphRagServiceConversation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraphRagServiceConversation.Conversation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Conversation', function() {
    it('should create an instance of Conversation', function() {
      // uncomment below and update the code to test Conversation
      //var instane = new GraphRagServiceConversation.Conversation();
      //expect(instance).to.be.a(GraphRagServiceConversation.Conversation);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GraphRagServiceConversation.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new GraphRagServiceConversation.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new GraphRagServiceConversation.Conversation();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new GraphRagServiceConversation.Conversation();
      //expect(instance).to.be();
    });

  });

}));
