/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraphRagServiceConversation);
  }
}(this, function(expect, GraphRagServiceConversation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraphRagServiceConversation.SendMessageResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SendMessageResult', function() {
    it('should create an instance of SendMessageResult', function() {
      // uncomment below and update the code to test SendMessageResult
      //var instane = new GraphRagServiceConversation.SendMessageResult();
      //expect(instance).to.be.a(GraphRagServiceConversation.SendMessageResult);
    });

    it('should have the property userMessage (base name: "userMessage")', function() {
      // uncomment below and update the code to test the property userMessage
      //var instane = new GraphRagServiceConversation.SendMessageResult();
      //expect(instance).to.be();
    });

    it('should have the property assistantMessage (base name: "assistantMessage")', function() {
      // uncomment below and update the code to test the property assistantMessage
      //var instane = new GraphRagServiceConversation.SendMessageResult();
      //expect(instance).to.be();
    });

  });

}));
