/**
 * Graph RAG Service - Conversation
 * Conversation and message storage with retrieval-augmented generation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GraphRagServiceConversation);
  }
}(this, function(expect, GraphRagServiceConversation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GraphRagServiceConversation.Source();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Source', function() {
    it('should create an instance of Source', function() {
      // uncomment below and update the code to test Source
      //var instane = new GraphRagServiceConversation.Source();
      //expect(instance).to.be.a(GraphRagServiceConversation.Source);
    });

    it('should have the property documentId (base name: "documentId")', function() {
      // uncomment below and update the code to test the property documentId
      //var instane = new GraphRagServiceConversation.Source();
      //expect(instance).to.be();
    });

    it('should have the property documentTitle (base name: "documentTitle")', function() {
      // uncomment below and update the code to test the property documentTitle
      //var instane = new GraphRagServiceConversation.Source();
      //expect(instance).to.be();
    });

    it('should have the property chunkId (base name: "chunkId")', function() {
      // uncomment below and update the code to test the property chunkId
      //var instane = new GraphRagServiceConversation.Source();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instane = new GraphRagServiceConversation.Source();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instane = new GraphRagServiceConversation.Source();
      //expect(instance).to.be();
    });

  });

}));
